### ISSUE TITLE
关于data中test.txt文件的问题

### ISSUE THREAD

**Issue by twjiang** [thunlp/NRE#1]
data压缩包中的test.txt文件中的关系类型基本部分都是NA？只有小部分数据正常给出关系类型。

**Comment by Mrlyk423** [comment]
数据来源于NYT10 (Sebastian Riedel, Limin Yao, and Andrew McCallum. Modeling relations and their mentions without labeled text.)，其中NA占大多数也比较符合现有文本中的情况。
