### ISSUE TITLE
Wrong Parameters of PCNN+ONE in models+figs 

### ISSUE THREAD

**Issue by KGIERE** [thunlp/NRE#12]
when I use the parameters in provided “models+figs” file to run the "test.cpp" in PCNN+ONE model, the result is apparent error.
![image 1](https://cloud.githubusercontent.com/assets/28531943/26043843/11b64166-3973-11e7-8d62-c721d7031bc0.png)

**Comment by Mrlyk423** [comment]
Maybe you set the wrong parameter?

**Comment by Mrlyk423** [comment]
You can check if the size of hidden state, word embedding is the same as that in my paper.
