### ISSUE TITLE
准确率计算是否包含NA类型

### ISSUE THREAD

**Issue by snowxiaoru** [thunlp/NRE#13]
你好，
在准确率计算的时候是否包含，NA类型？因为训练语料中 NA类型数据占比近80%，所以很多数据会极有可能预测为NA类型，而测试数据中NA占近90%，所以如果包含NA类型，准确率确实很高，但是如果去除NA类型计算的准确率非常低。

**Comment by Mrlyk423** [comment]
不包含。
