### ISSUE TITLE
Entity order while building distant supervision dataset

### ISSUE THREAD

**Issue by swbliss** [thunlp/NRE#15]
How did you (or Riedel) configure the dataset regarded to the order of entities in sentence.

In training set, there are instances related with both entity pair (e1, e2) and another pair (e2, e1).

In addition, not only those entity pairs don't share sentence instances (relation mentions), but also each pair doesn't have any order of appearance of entities. (I mean, for (e1, e2) entity pair, there are both sentence in which e1 appears before e2, and e2 appears before e1)

I think the order of entities is important as PCNN uses position embedding. 

If there is no triple related with (e1, e2) entity pair in Freebase, what sentences are assigned for training instance for (e1, e2)-None and what sentences are assigned for (e2, e1)-None?

Thank you :)

**Comment by Mrlyk423** [comment]
The dataset is build by "Modeling relations and their mentions without labeled text." You can refer to this paper.
