### ISSUE TITLE
关于relation2id.txt

### ISSUE THREAD

**Issue by twjiang** [thunlp/NRE#2]
在加载train.txt数据时发现存在不在relation2id.txt的关系类型，如：/people/ethnicity/includes_groups ,阅读NRE中代码发现似乎将其看做NA关系。
请问，这些未记录到relation2id.txt的关系，是因为其出现的次数过少吗？如果是这样的话，将其处理为NA或直接忽略都可以吗？

**Comment by Mrlyk423** [comment]
对的，都可以。
