### ISSUE TITLE
PCNN+ATT has no attentions

### ISSUE THREAD

**Issue by unknownstar88** [thunlp/NRE#3]
Hi.
when I read the codes one by one, I found PCNN+ATT don't have any attention part while CNN+ATT has that.

Concretely, "init.h" in the "CNN+ATT" directory mentions the attention-related matrix called "att_W" and "att_W_Dao" which are used and trained in the trainining step of "train.cpp" but in "PCNN+ATT", I haven't found the parts.

Could you check them??

**Comment by pvthuy** [comment]
Hi, did you find the answer?
