### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by SharmisthaJat** [thunlp/NRE#4]
Hi,

Thanks for sharing your code. I am running this on a linux server with 60GB free memory. Compile works fine, but ./train leads to a segmentation fault.
-------------------------------------------
[s CNN+ATT]$ ls
init.h  log.txt  makefile  out  test.cpp  test.h  train.cpp
[s CNN+ATT]$ make
g++ train.cpp -o train -O2 -lpthread
g++ test.cpp -o test -O2 -lpthread
[sharmistha@momo CNN+ATT]$ ./train
Init Begin.
Segmentation fault (core dumped)
-------------------------------------------------------
All the training files are in the correct directory. Please let me know how to resolve this issue.

Thanks

**Comment by Mrlyk423** [comment]
Please sure that you have unzipped the data.zip in data folder.

**Comment by SharmisthaJat** [comment]
data is unzipped in the data folder. Following are the contents,

[s]$ ls data/
att.test   data      entity2id.txt    test.txt   vec.bin
att.train  data.zip  relation2id.txt  train.txt  vector1.txt

Do I need anything else in the data folder to make this work ?

**Comment by Mrlyk423** [comment]
Please follow the original data location after unzipping. The files expect "vec.bin" need to be placed in the folder "RE".

**Comment by SharmisthaJat** [comment]
Thanks, Moving vec.bin to RE works. 

I had one more unrelated question. Original Riedel 2010 dataset had about 120k training instances and around 180k test instances. While, your training dataset is bigger. The procedure of constructing the training set is same, so what has changed to yield more examples in train set ?

**Comment by SharmisthaJat** [comment]
I had a minor question. The MultiR dataset contained about 120k train examples and 180k test examples in the protocol buffer format. While you have almost 522611train examples. Did you preprocess the data again from the riedel dataset ? and if so what was the process like.
