### ISSUE TITLE
The pr.txt files does not match the curve in the paper

### ISSUE THREAD

**Issue by bfluo** [thunlp/NRE#5]
Hi,

I'm trying to reproduce the PR curves in the paper. However I find that the pr.txt files in the repository does not match the curves reported in the paper (PCNN+ATT for example). 

Are these files generated by models that are not fully trained? 
Can you provide pr.txt files that can reproduce curves in the paper?

Much appreciated.

**Comment by SharmisthaJat** [comment]
I have the same questions. pr-1.txt has 2000 lines, shouldn't it have more than ~96k lines (more than one prediction for each entity pair in test file). I changed line 237 of test.h to {for (int i=0; i<int(aa.size()); i++)} which results in ~96k*52 lines in pr.txt. But, the graph still does not match. 

It will be very helpful if you could provide us with the right script to generate the PR curve. 

Thanks

**Comment by Mrlyk423** [comment]
I have updated the test.h in PCNN+ATT. And the original pr.txt and models of our experiments can be downloaded in https://pan.baidu.com/s/1bo0fgXx.

**Comment by bfluo** [comment]
Thank you! @Mrlyk423 
This helps a lot!

**Comment by SharmisthaJat** [comment]
Thanks for your response
