### ISSUE TITLE
First word match could be not right entity mention.

### ISSUE THREAD

**Issue by sergii-gavrylov** [thunlp/NRE#7]
From this [line](https://github.com/thunlp/NRE/blob/master/CNN%2BONE/init.h#L190) of code, It seems that the first match between a head(tail) entity and a word is treated as right entity mention in the sentence. But in the case when a sentence has several mentions of the entity it is not necessarily true.  
```
head: brooklyn
tail: eastern parkway
sentence: brooklyn museum , 200 eastern parkway , brooklyn , (718) 638-5000 .
```
Original [dataset](http://iesl.cs.umass.edu/riedel/ecml/) contains necessary index information, but it seems that preprocessed data in this repo doesn't have it.

Please correct me if I am wrong.

**Comment by Mrlyk423** [comment]
We find that the index information have no influence of the final performance in this dataset. Hence, in this code, we just ignore it. Thanks.
