### ISSUE TITLE
关于train时最后一遍迭代和test时准确率召回率一样的问题

### ISSUE THREAD

**Issue by aiyouweixiaoxia** [thunlp/NRE#9]
您好：
我在使用您的代码时，完全按照您的readme进行操作，之后发现输出在屏幕上的train最后一遍的p,r值和test一致。刚刚开始学习自然语言处理，不知道怎么回事，所以麻烦您了。
`./train`
`…`
`tot:1950`
`persicon:1 recall :0.00512821`
`persicon:0.782178 recall :0.0405128`
`…`

`./test`
`tot:1950`
`persicon:1 recall :0.00512821`
`persicon:0.782178 recall :0.0405128`
`…`

**Comment by Mrlyk423** [comment]
训练完毕后做了一次测试。
